export const API_URL =
  window.location.hostname === 'localhost'
    ? 'http://localhost:8000/api/v1'
    : 'https://api.biramedia.com/api/v1';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const GET_PENDING_ACCOUNTS_SUCCESS = 'GET_PENDING_ACCOUNTS_SUCCESS';
export const GET_PENDING_ACCOUNTS_FAILED = 'GET_PENDING_ACCOUNTS_FAILED';
export const UPDATE_USER_ACCOUNT_SUCCESS = 'UPDATE_USER_ACCOUNT_SUCCESS';
export const UPDATE_USER_ACCOUNT_FAILED = 'UPDATE_USER_ACCOUNT_FAILED';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILED = 'UPDATE_USER_INFO_FAILED';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAILED = 'UPDATE_USER_PROFILE_FAILED';
export const DEACTIVATE_USER_SUCCESS = 'DEACTIVATE_USER_SUCCESS';
export const DEACTIVATE_USER_FAILED = 'DEACTIVATE_USER_FAILED';
export const UPDATE_BLOCK_STATUS_SUCCESS = 'UPDATE_BLOCK_STATUS_SUCCESS';
export const UPDATE_BLOCK_STATUS_FAILED = 'UPDATE_BLOCK_STATUS_FAILED';
export const REGISTER_USER_BY_ADMIN_SUCCESS = 'REGISTER_USER_BY_ADMIN_SUCCESS';
export const REGISTER_USER_BY_ADMIN_FAILED = 'REGISTER_USER_BY_ADMIN_FAILED';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';

// --------------------Profile---------------------------//
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_FAILED = 'UPLOAD_PROFILE_IMAGE_FAILED';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';
export const SET_THEME = 'SET_THEME';

// -------------------Leads ----------------------------//
export const CREATE_LEAD_SUCCESS = 'CREATE_LEAD_SUCCESS';
export const CREATE_LEAD_FAILED = 'CREATE_LEAD_FAILED';
export const GET_LEAD_LIST_SUCCESS = 'GET_LEAD_LIST_SUCCESS';
export const GET_LEAD_LIST_FAILED = 'GET_LEAD_LIST_FAILED';
export const SEARCH_LEAD_SUCCESS = 'SEARCH_LEAD_SUCCESS';
export const GET_TWILIO_TOKEN_SUCCESS = 'GET_TWILIO_TOKEN_SUCCESS';
export const SET_ONGOING_CALL_STATUS = 'SET_ONGOING_CALL_STATUS';
export const STORE_OUTGOING_CALL_SUCCESS = 'STORE_OUTGOING_CALL_SUCCESS';
export const GET_LEAD_BY_ID_SUCCESS = 'GET_LEAD_BY_ID_SUCCESS';
export const GET_AGENT_CALL_DETAILS_SUCCESS = 'GET_AGENT_CALL_DETAILS_SUCCESS';
export const UPDATE_CALL_STATUS_SUCCESS = 'UPDATE_CALL_STATUS_SUCCESS';
export const STORE_CURRENT_LEAD_ID = 'STORE_CURRENT_LEAD_ID';
export const UPDATE_LEAD_COMMENTS = 'UPDATE_LEAD_COMMENTS';

// ---------------------Event-------------------------//
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILED = 'CREATE_EVENT_FAILED';
export const GET_EVENT_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';
export const GET_EVENT_LIST_FAILED = 'GET_EVENT_LIST_FAILED';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILED = 'UPDATE_EVENT_FAILED';
export const UPLOAD_BULK_LEAD_SUCCESS = 'UPLOAD_BULK_LEAD_SUCCESS';
export const UPLOAD_BULK_LEAD_FAILED = 'UPLOAD_BULK_LEAD_FAILED';
export const REMOVE_PROFILE_IMAGE = 'REMOVE_PROFILE_IMAGE';

// --------------------Agent Management------------------ //
export const SET_SELECTED_AGENT_TO_DISPLAY = 'SET_SELECTED_AGENT_TO_DISPLAY';

// --------------------Call Center------------------ //
export const SET_SELECTED_LEAD = 'SET_SELECTED_LEAD';

export const SET_DIAL_STATUS = 'SET_DIAL_STATUS';
export const SET_TW_TOKEN = 'SET_TW_TOKEN';
